apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: avalier-tcp-proxy
  #namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: avalier-tcp-proxy
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70


 