apiVersion: v1
kind: Service
metadata:
  name: avalier-tcp-proxy
  labels:
    app: avalier-tcp-proxy
spec:
  selector:
    app: avalier-tcp-proxy
  ports:
  - protocol: TCP
    port: 1491
    targetPort: 1491
  - protocol: TCP
    port: 1492
    targetPort: 1492
